version: '3.4'

services:

  programminglanguages_redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - shared-programminglanguages-net

  programminglanguages_rabbitmq:
    ports:
      - "25672:5672"
      - "25673:5673"
      - "35672:15672" 
    networks:
      - shared-programminglanguages-net
    volumes:      
      - rabbitmq-data:/var/lib/rabbitmq/

  programminglanguages_postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=postgres
    networks:
      - shared-programminglanguages-net
    ports:
      - "25432:5432"
    volumes:
      - postgresvolume:/var/lib/postgresql/data

  programminglanguages_api:
    ports:
      - "20000:80"
    networks:
      - shared-programminglanguages-net
    env_file:
      - env.api
  
  programminglanguages_identity:
    ports:
      - "20001:80"
    networks:
      - shared-programminglanguages-net
    env_file:
      - env.identity

  programminglanguages_web:
    ports:
      - "20002:80"
    networks:
      - shared-programminglanguages-net

  programminglanguages_worker:
    ports:
      - "20003:80"
    networks:
      - shared-programminglanguages-net
    env_file:
      - env.worker

volumes:
  postgresvolume:
  rabbitmq-data:

networks:
  shared-programminglanguages-net:
    name: ProgrammingLanguages
    driver: bridge


