version: '3.4'

services:
  programminglanguages_redis:
    image: redis

  programminglanguages_postgres:
    image: postgres

  programminglanguages_rabbitmq:
    image: rabbitmq:3-management

  programminglanguages_api:
    image: ${DOCKER_REGISTRY-}programminglanguagesapi
    build:
      context: .
      dockerfile: System/Api/ProgrammingLanguages.Api/Dockerfile
    depends_on:
      - programminglanguages.redis
      - programminglanguages_rabbitmq 
      - programminglanguages.postgres

  programminglanguages_identity:
    image: ${DOCKER_REGISTRY-}programminglanguagesidentity
    build:
      context: .
      dockerfile: System/Identity/ProgrammingLanguages.Identity/Dockerfile
    depends_on:
      - programminglanguages.redis
      - programminglanguages_rabbitmq 
      - programminglanguages.postgres

  programminglanguages_web:
    image: ${DOCKER_REGISTRY-}programminglanguage
    build:
      context: .
      dockerfile: System/Web/ProgrammingLanguage.Web/Dockerfile
    depends_on:
      - programminglanguages_redis
      - programminglanguages_rabbitmq 
      - programminglanguages_postgres     

  programminglanguages.worker:
    image: ${DOCKER_REGISTRY-}programminglanguage
    build:
      context: .
      dockerfile: System/Worker/ProgrammingLanguage.Worker/Dockerfile
    depends_on:
      - programminglanguages_postgres
      - programminglanguages_rabbitmq 
      - programminglanguages_redis 

  

